name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: test
      uses: grandcolline/golang-github-actions@versionup
      with:
        githubToken: abc
        command: fmt
