name: Go
on: [pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@master
    - name: test
      uses: grandcolline/golang-github-actions@versionup
      with:
        command: lint
        githubToken: ${{ secrets.GITHUB_TOKEN }}
      env:
        HOGE: "fooooo"
      arg:
        GO111MODULE: "on"

